### ISSUE TITLE
Publish First Public Working Draft of Input Events?

### ISSUE THREAD

**Issue by chaals** [w3c/input-events#1]
Please +1 / -1 on this issue, or reply to the thread on public-webapps, before the end of the day 22 August 2016. It is unnecessary to do both.

**Comment by domenic** [comment]
This spec uses invalid Web IDL syntax (`StaticRange[]`), so it seems like it should probably get cleaned up before being advanced any further.

**Comment by johanneswilm** [comment]
@domenic: What would the correct syntax be for "Array of StaticRange instances"?

**Comment by domenic** [comment]
I filed #2 to track that (and include a suggestion). I'm going through and filing other issues as I find them as well.

**Comment by johanneswilm** [comment]
As discussed in #2, it turns out that the editor's draft specifying the Web IDL syntax no longer supports the `StaticRange[]` syntax, but the latests candidate recommendation does. As recommended by @domenic, I have therefore changed it in the editor's draft of the input events spec to work as specified in the editor's draft of the Web IDL spec.

**Comment by johanneswilm** [comment]
Publication has taken place: https://www.w3.org/TR/2016/WD-input-events-20160830/
